Update README.md
mrsaicharan1/PyDic pull request #12
Opened 2018-01-10 06:30 UTC by AbhiTaker

the updated form of readme.md which helps in better understanding of the working of project

2018-01-10 07:44 UTC, mrsaicharan1 requested changes
Please re-write without any grammatical mistakes. Take care of sentence formation.

2018-01-11 02:36 UTC, mrsaicharan1 commented on README.md
> +* appropriate message is displayed if the required word doesn't exists in database
exist*

2018-01-11 07:28 UTC, AbhiTaker commented
corrected the spelling

2018-01-11 10:24 UTC, mrsaicharan1 commented
Shows some conflicts. Please fix. @AbhiTaker

2018-01-11 11:33 UTC, AbhiTaker commented
conflicts resolved

2018-01-11 16:17 UTC, merged